name: trippy
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  fluttertoast: ^8.0.8
  collection: ^1.15.0
  sliding_up_panel: ^2.0.0+1
  kakao_map_plugin: ^0.1.6
  provider: ^5.0.0
  animated_notch_bottom_bar: ^1.0.0
  google_fonts: ^4.0.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Dmsans
      fonts:
      - asset: assets/fonts/DMSans-Thin.ttf
        weight: 100
      - asset: assets/fonts/DMSans-Light.ttf
        weight: 300
      - asset: assets/fonts/DMSans-Regular.ttf
        weight: 400
      - asset: assets/fonts/DMSans-Medium.ttf
        weight: 500
      - asset: assets/fonts/DMSans-Bold.ttf
        weight: 700
      - asset: assets/fonts/DMSans-Black.ttf
        weight: 900
    - family: Bm
      fonts:
        - asset: assets/fonts/bm.ttf
          weight: 400
    - family: As
      fonts:
        - asset: assets/fonts/SCDream1.otf
          weight: 100
        - asset: assets/fonts/SCDream2.otf
          weight: 200
        - asset: assets/fonts/SCDream3.otf
          weight: 300
        - asset: assets/fonts/SCDream4.otf
          weight: 400
        - asset: assets/fonts/SCDream5.otf
          weight: 500
        - asset: assets/fonts/SCDream6.otf
          weight: 600
        - asset: assets/fonts/SCDream7.otf
          weight: 700
        - asset: assets/fonts/SCDream8.otf
          weight: 800
        - asset: assets/fonts/SCDream9.otf
          weight: 900
    - family: Air
      fonts:
        - asset: assets/fonts/AirbnbCereal_W_Bk.otf
          weight: 300
        - asset: assets/fonts/AirbnbCereal_W_Md.otf
          weight: 500
        - asset: assets/fonts/AirbnbCereal_W_Bd.otf
          weight: 700